<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-63OQNSJ" failures="1" tests="7" name="RetryFailedTestCase" time="0.256" errors="0" timestamp="2023-11-06T16:46:26 IST">
  <testcase classname="runFailedTcs.RunFailedTC" name="tc1" time="0.022"/>
  <testcase classname="runFailedTcs.RunFailedTC" name="tc2" time="0.021">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase classname="runFailedTcs.RunFailedTC" name="tc2" time="0.008">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase classname="runFailedTcs.RunFailedTC" name="tc2" time="0.017">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase classname="runFailedTcs.RunFailedTC" name="tc2" time="0.005">
    <skipped/>
  </testcase> <!-- tc2 -->
  <testcase classname="runFailedTcs.RunFailedTC" name="tc2" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runFailedTcs.RunFailedTC.tc2(RunFailedTC.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- tc2 -->
  <testcase classname="runFailedTcs.RunFailedTC" name="tc3" time="0.002"/>
</testsuite> <!-- RetryFailedTestCase -->
